<?php
/**
 * @file
 * Code for the Stanford News Extras feature.
 */

include_once 'stanford_news_extras.features.inc';

/**
 * Implementation of hook_form_alter()
 */
/*
function stanford_news_extras_form_alter(&$form, &$form_state, $form_id) {

  // Targeting the news item edit form
  if ($form_id == "stanford_news_item_node_form") {
    $form['title']['#description'] = t('This is the title for your news item. '
      . 'Please keep this title under 70 characters.');
    $form['field_s_image_info']['und']['0']['field_s_image_caption']['und']['#description'] =
      t("Use this field to display both the image caption and credits for the photographer or organization. "
        . "Enter the caption, a pipe '|', and the credits.");
    $form['field_s_image_info']['und']['0']['field_s_image_credits']['und']['#description'] =
      t("Leave this field blank. "
        . "Please use the caption field to display both the credits and the caption.");
    dsm($form);
    dsm($form_state);
  }
}
*/

/**
 * Implementation of hook_form_alter()
 */
function stanford_news_extras_form_stanford_news_item_node_form_alter(&$form, &$form_state, $form_id) {

  // Targeting the news item edit form
  if ($form_id == "stanford_news_item_node_form") {
    $form['title']['#description'] = t('This is the title for your news item. '
      . 'Please keep this title under 70 characters.');
    $form['field_s_image_info']['und']['0']['field_s_image_caption']['und']['#description'] =
      t("Use this field to display both the image caption and credits for the photographer or organization. "
        . "Enter the caption, a pipe '|', and the credits.");
    $form['field_s_image_info']['und']['0']['field_s_image_credits']['und']['#description'] =
      t("Leave this field blank. "
        . "Please use the caption field to display both the credits and the caption instead.");
    dsm($form);
    dsm($form_state);
  }

}

/**
 * Implementation of hook_block_view_alter()
 */
function stanford_news_extras_block_view_alter(&$data, $block) {
  // Remove title on blocks.
  if ($block->bid == 'ds_extras-banner') {
    $data['title'] = '<none>';
  }
  else if ($block->bid == 'ds_extras-banner_overlay') {
    $data['title'] = '<none>';
  }
}
