<?php
/**
 * @file
 * Code for the Stanford News Extras feature.
 */

include_once 'stanford_news_extras.features.inc';

/*
 * Implementation of hook_form_alter()
 */
function stanford_news_extras_form_alter(&$form, &$form_state, $form_id) {

  // target a single form
  if($form_id == "stanford_news_item_node_form"){
    $form['title']['#description'] = t('This is the title for your news item. '
      . 'Please keep this title under 70 characters');
  }
}
