# Blank config file so that Circle won't give us failing tests.
version: 2

## Defines images and working directory.
defaults: &defaults
  docker:
    - image: pookmish/drupal8ci:pcov
    - image: selenium/standalone-chrome:3.141.59-neon
    - image: mariadb:10.3
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
  working_directory: /var/www/html

jobs:

