<?php
/**
 * @file
 * Code for the Stanford News Views feature.
 */

include_once 'stanford_news_views.features.inc';

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_news_views_preprocess_views_view(&$vars) {
  if (array_search('masonry', $vars['classes_array']) !== FALSE) {
    $path = drupal_get_path('module', 'stanford_news_views');
    drupal_add_js("$path/vendor/imagesloaded.min.js");
    drupal_add_js("$path/vendor/masonry.min.js");
    drupal_add_js("$path/js/stanford_news_views.js");
    drupal_add_css("$path/css/stanford_news_views.css");
  }
}